// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-playground/validator/v10"
	"net/http"
	"online-shop-api/controller"
	"online-shop-api/middleware"
	"online-shop-api/repository"
	"online-shop-api/service"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	categoryRepository := repository.NewCategoryRepository()
	db := NewDB()
	v := ProvideValidatorOptions()
	validate := validator.New(v...)
	categoryService := service.NewCategoryService(categoryRepository, db, validate)
	categoryController := controller.NewCategoryController(categoryService)
	productRepository := repository.NewProductRepository()
	productService := service.NewProductService(productRepository, categoryService, db, validate)
	productController := controller.NewProductController(productService)
	userRepository := repository.NewUserRepository()
	authService := service.NewAuthService(userRepository, db, validate)
	authController := controller.NewAuthController(authService)
	router := NewRouter(categoryController, productController, authController)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

func ProvideValidatorOptions() []validator.Option {
	return []validator.Option{}
}
